import { useEffect, useState } from "react";
import { toast } from "sonner";
import { motion } from "framer-motion";
import { Search, Sparkles, AlertTriangle, CheckCircle2, Wand2, Copy, Plus, Trash2, History } from "lucide-react";
import api, { streamPost } from "../lib/api";
import { useAuth } from "../context/AuthContext";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "../components/ui/tabs";

const SEV = { high: "bg-destructive/15 text-red-400 border-destructive/30", medium: "bg-amber-500/15 text-amber-400 border-amber-500/30", low: "bg-white/5 text-muted-foreground border-border" };

function ScannerTab() {
  const { business } = useAuth();
  const [url, setUrl] = useState(business?.website || "");
  const [scanning, setScanning] = useState(false);
  const [audit, setAudit] = useState(null);
  const [recs, setRecs] = useState(null);
  const [loadingRecs, setLoadingRecs] = useState(false);
  const [history, setHistory] = useState([]);

  const loadHistory = async () => { const { data } = await api.get("/seo/audits"); setHistory(data.audits); if (data.audits[0]) setAudit(data.audits[0]); };
  useEffect(() => { loadHistory(); }, []);

  const scan = async () => {
    if (!url) return toast.error("Enter a website URL");
    setScanning(true); setRecs(null);
    try {
      const { data } = await api.post("/seo/scan", { url });
      setAudit(data);
      loadHistory();
      toast.success(`Scan complete — score ${data.score}`);
    } catch (e) {
      toast.error(e.response?.data?.detail || "Scan failed");
    } finally { setScanning(false); }
  };

  const getRecs = async () => {
    if (!audit) return;
    setLoadingRecs(true);
    try {
      const { data } = await api.get(`/seo/audits/${audit.audit_id}/recommendations`);
      setRecs(data);
      toast.success(`Generated by ${data.model}`);
    } catch (e) { toast.error("Could not get recommendations"); }
    finally { setLoadingRecs(false); }
  };

  return (
    <div className="space-y-6">
      <div className="rounded-xl border border-border bg-card p-6">
        <Label>Website to scan</Label>
        <div className="flex gap-3 mt-2">
          <Input data-testid="seo-url-input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://yourbusiness.com" />
          <Button data-testid="seo-scan-btn" onClick={scan} disabled={scanning} className="rounded-full shrink-0">
            <Search className="h-4 w-4 mr-1" /> {scanning ? "Scanning…" : "Scan now"}
          </Button>
        </div>
      </div>

      {audit && (
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="grid lg:grid-cols-3 gap-5">
          <div className="rounded-xl border border-border bg-card p-6 flex flex-col items-center justify-center">
            <div className="font-heading font-black text-6xl text-white">{audit.score}</div>
            <div className="text-xs uppercase tracking-[0.2em] text-muted-foreground mt-1">SEO Health</div>
            <div className="text-xs text-muted-foreground mt-3 truncate max-w-full">{audit.url}</div>
            <Button data-testid="seo-get-recs-btn" onClick={getRecs} disabled={loadingRecs} className="rounded-full mt-4 w-full">
              <Sparkles className="h-4 w-4 mr-1" /> {loadingRecs ? "Thinking…" : "Fix this for me"}
            </Button>
          </div>

          <div className="lg:col-span-2 rounded-xl border border-border bg-card p-6">
            <h3 className="font-heading font-bold text-lg mb-1">We found {audit.issues.length} thing{audit.issues.length !== 1 ? "s" : ""} to improve</h3>
            <p className="text-sm text-muted-foreground mb-4">In plain English — what's helping and what's holding you back.</p>
            <div className="space-y-3">
              {audit.issues.length === 0 && <div className="flex items-center gap-2 text-emerald-400"><CheckCircle2 className="h-5 w-5" /> Your site looks great!</div>}
              {audit.issues.map((iss, i) => (
                <div key={i} data-testid={`seo-issue-${iss.key}`} className={`rounded-lg border p-3 ${SEV[iss.severity]}`}>
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4" />
                    <span className="font-medium text-white">{iss.title}</span>
                    <span className="ml-auto text-[10px] uppercase tracking-wider">{iss.severity}</span>
                  </div>
                  <p className="text-sm mt-1 text-muted-foreground">{iss.detail}</p>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      )}

      {recs && (
        <div className="rounded-xl border border-primary/30 bg-primary/5 p-6">
          <div className="flex items-center gap-2 mb-4"><Sparkles className="h-5 w-5 text-primary" /><h3 className="font-heading font-bold text-lg">AI Recommendations</h3>
            <span className="text-[10px] uppercase text-muted-foreground border border-border rounded-full px-2 py-0.5">{recs.provider}</span></div>
          <div className="space-y-3">
            {recs.recommendations.map((r, i) => (
              <div key={i} className="rounded-lg border border-border bg-card p-4">
                <div className="flex items-center justify-between"><span className="font-medium text-white">{r.title}</span>
                  <span className="text-[10px] uppercase tracking-wider bg-white/5 px-2 py-0.5 rounded-full text-muted-foreground">{r.effort}</span></div>
                <p className="text-sm text-muted-foreground mt-1.5">{r.recommendation}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {history.length > 0 && (
        <div className="rounded-xl border border-border bg-card p-6">
          <div className="flex items-center gap-2 mb-4"><History className="h-4 w-4 text-muted-foreground" /><h3 className="font-medium">Audit history</h3></div>
          <div className="space-y-2">
            {history.map((h) => (
              <button key={h.audit_id} data-testid={`audit-history-${h.audit_id}`} onClick={() => { setAudit(h); setRecs(null); }}
                className="w-full flex items-center justify-between text-sm p-2 rounded-lg hover:bg-white/5 transition-colors">
                <span className="text-muted-foreground truncate">{h.url}</span>
                <span className="text-xs text-muted-foreground">{(h.created_at || "").slice(0, 10)}</span>
                <span className="font-mono text-white ml-3">{h.score}</span>
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function GeneratorTab() {
  const [form, setForm] = useState({ page_type: "service", topic: "", keywords: "" });
  const [output, setOutput] = useState("");
  const [streaming, setStreaming] = useState(false);

  const generate = async () => {
    if (!form.topic) return toast.error("Enter a topic");
    setOutput(""); setStreaming(true);
    try {
      await streamPost("/seo/generate-page", form, (_chunk, full) => setOutput(full));
      toast.success("Page ready — review before publishing");
    } catch (e) { toast.error("Generation failed"); }
    finally { setStreaming(false); }
  };

  return (
    <div className="grid lg:grid-cols-2 gap-5">
      <div className="rounded-xl border border-border bg-card p-6 space-y-4 h-fit">
        <div>
          <Label>Page type</Label>
          <select data-testid="gen-type" value={form.page_type} onChange={(e) => setForm({ ...form, page_type: e.target.value })}
            className="mt-1.5 w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
            <option value="service">Service page</option>
            <option value="local">Local / city page</option>
          </select>
        </div>
        <div><Label>Topic / service</Label><Input data-testid="gen-topic" value={form.topic} onChange={(e) => setForm({ ...form, topic: e.target.value })} placeholder="Weekly pool cleaning" className="mt-1.5" /></div>
        <div><Label>Target keywords</Label><Input data-testid="gen-keywords" value={form.keywords} onChange={(e) => setForm({ ...form, keywords: e.target.value })} placeholder="pool cleaning austin, pool maintenance" className="mt-1.5" /></div>
        <Button data-testid="gen-btn" onClick={generate} disabled={streaming} className="w-full rounded-full">
          <Wand2 className="h-4 w-4 mr-1" /> {streaming ? "Writing…" : "Generate page"}
        </Button>
        <p className="text-xs text-muted-foreground">AI writes it. You review and approve before anything goes live.</p>
      </div>
      <div className="rounded-xl border border-border bg-card p-6 min-h-[300px]">
        <div className="flex items-center justify-between mb-3">
          <span className="text-xs uppercase tracking-wider text-muted-foreground">Preview {streaming && <span className="text-primary">· streaming</span>}</span>
          {output && <Button data-testid="copy-page-btn" onClick={() => { navigator.clipboard.writeText(output); toast.success("Copied"); }} variant="ghost" size="sm"><Copy className="h-4 w-4" /></Button>}
        </div>
        <pre data-testid="gen-output" className="whitespace-pre-wrap text-sm text-muted-foreground font-mono leading-relaxed">{output || "Your generated page will appear here…"}{streaming && <span className="inline-block w-2 h-4 bg-primary animate-pulse ml-0.5" />}</pre>
      </div>
    </div>
  );
}

function TrackingTab() {
  const [keywords, setKeywords] = useState([]);
  const [competitors, setCompetitors] = useState([]);
  const [kw, setKw] = useState("");
  const [comp, setComp] = useState({ name: "", website: "" });

  const load = async () => {
    const [k, c] = await Promise.all([api.get("/seo/keywords"), api.get("/seo/competitors")]);
    setKeywords(k.data.keywords); setCompetitors(c.data.competitors);
  };
  useEffect(() => { load(); }, []);

  const addKw = async () => { if (!kw) return; await api.post("/seo/keywords", { keyword: kw }); setKw(""); load(); };
  const addComp = async () => { if (!comp.name) return; await api.post("/seo/competitors", comp); setComp({ name: "", website: "" }); load(); };

  return (
    <div className="grid md:grid-cols-2 gap-5">
      <div className="rounded-xl border border-border bg-card p-6">
        <h3 className="font-heading font-bold text-lg mb-3">Keywords</h3>
        <div className="flex gap-2 mb-4">
          <Input data-testid="kw-input" value={kw} onChange={(e) => setKw(e.target.value)} placeholder="pool cleaning austin" />
          <Button data-testid="add-kw-btn" onClick={addKw} className="rounded-full shrink-0"><Plus className="h-4 w-4" /></Button>
        </div>
        <div className="space-y-2">
          {keywords.length === 0 && <p className="text-sm text-muted-foreground">Track the search terms you want to rank for.</p>}
          {keywords.map((k) => (
            <div key={k.keyword_id} className="flex items-center justify-between text-sm p-2 rounded-lg bg-background border border-border">
              <span className="text-white">{k.keyword}</span>
              <button data-testid={`del-kw-${k.keyword_id}`} onClick={async () => { await api.delete(`/seo/keywords/${k.keyword_id}`); load(); }} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button>
            </div>
          ))}
        </div>
      </div>
      <div className="rounded-xl border border-border bg-card p-6">
        <h3 className="font-heading font-bold text-lg mb-3">Competitors</h3>
        <div className="flex gap-2 mb-4">
          <Input data-testid="comp-name" value={comp.name} onChange={(e) => setComp({ ...comp, name: e.target.value })} placeholder="Competitor name" />
          <Button data-testid="add-comp-btn" onClick={addComp} className="rounded-full shrink-0"><Plus className="h-4 w-4" /></Button>
        </div>
        <div className="space-y-2">
          {competitors.length === 0 && <p className="text-sm text-muted-foreground">Keep an eye on who you're up against.</p>}
          {competitors.map((c) => (
            <div key={c.competitor_id} className="flex items-center justify-between text-sm p-2 rounded-lg bg-background border border-border">
              <span className="text-white">{c.name}</span>
              <button data-testid={`del-comp-${c.competitor_id}`} onClick={async () => { await api.delete(`/seo/competitors/${c.competitor_id}`); load(); }} className="text-muted-foreground hover:text-destructive"><Trash2 className="h-3.5 w-3.5" /></button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export default function ScaleSEO() {
  return (
    <div className="space-y-6">
      <div>
        <div className="text-[10px] uppercase tracking-[0.2em] text-muted-foreground">ScaleSEO</div>
        <h1 className="font-heading font-black text-3xl tracking-tight mt-1">Get found online</h1>
      </div>
      <Tabs defaultValue="scanner">
        <TabsList className="bg-card">
          <TabsTrigger data-testid="tab-scanner" value="scanner">Scanner</TabsTrigger>
          <TabsTrigger data-testid="tab-generator" value="generator">Page Generator</TabsTrigger>
          <TabsTrigger data-testid="tab-tracking" value="tracking">Keywords & Competitors</TabsTrigger>
        </TabsList>
        <TabsContent value="scanner" className="mt-6"><ScannerTab /></TabsContent>
        <TabsContent value="generator" className="mt-6"><GeneratorTab /></TabsContent>
        <TabsContent value="tracking" className="mt-6"><TrackingTab /></TabsContent>
      </Tabs>
    </div>
  );
}
